# Generated by Django 5.2.11 on 2026-03-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='intent',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('booking_select_spec', 'Booking - Select Specialization'), ('booking_select_doctor', 'Booking - Select Doctor'), ('booking_select_date', 'Booking - Select Date'), ('booking_select_slot', 'Booking - Select Time Slot'), ('booking_confirm', 'Booking - Confirm'), ('reschedule_select_appt', 'Reschedule - Select Appointment'), ('reschedule_select_date', 'Reschedule - Select New Date'), ('reschedule_select_slot', 'Reschedule - Select New Slot'), ('cancel_select_appt', 'Cancel - Select Appointment'), ('cancel_confirm', 'Cancel - Confirm'), ('symptom_check', 'Symptom Check'), ('registration', 'Registration'), ('awaiting_input', 'Awaiting Input')], default='idle', max_length=30),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=5),
        ),
    ]
