# Generated by Django 5.2.11 on 2026-03-07 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('appt_confirmed', 'Appointment Confirmed'), ('appt_reminder_24h', 'Appointment Reminder 24h'), ('appt_reminder_1h', 'Appointment Reminder 1h'), ('appt_rescheduled', 'Appointment Rescheduled'), ('appt_cancelled_doc', 'Appointment Cancelled by Doctor'), ('appt_completed', 'Appointment Completed'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('payment_refund', 'Refund Processed'), ('doctor_available', 'Doctor Available Today'), ('new_doctor', 'New Doctor Added'), ('prescription_uploaded', 'Prescription Uploaded'), ('diet_plan_ready', 'Diet Plan Ready'), ('profile_reminder', 'Profile Update Reminder'), ('new_booking', 'New Appointment Booked'), ('appt_cancelled_pat', 'Appointment Cancelled by Patient'), ('appt_reminder_30m', 'Appointment Reminder 30min'), ('reschedule_request', 'Reschedule Request'), ('payment_received', 'Payment Received'), ('daily_earnings', 'Daily Earnings Summary'), ('new_patient', 'New Patient Registered'), ('review_received', 'Review Received'), ('profile_verified', 'Profile Verified'), ('new_doctor_reg', 'New Doctor Registration'), ('doctor_verify_req', 'Doctor Verification Request'), ('high_traffic', 'High Appointment Traffic'), ('payment_issue', 'Payment Issue'), ('system_alert', 'System Alert')], max_length=30)),
                ('category', models.CharField(choices=[('appointment', 'Appointment'), ('payment', 'Payment'), ('health', 'Health'), ('system', 'System')], default='system', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
